
name: CI/CD du Package Node.js

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test_and_lint:
    name: ğŸ§ª Tests TypeScript (Jest)
    runs-on: ubuntu-latest 
    steps:
    - name: â¬‡ï¸ Checkout du Code
      uses: actions/checkout@v4
    - name: ğŸ› ï¸ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm' 

    - name: ğŸ“¥ Installation des DÃ©pendances
      run: npm ci 

    - name: ğŸ”¬ ExÃ©cution des Tests Unitaires et GÃ©nÃ©ration du Coverage
      run: npm test